### ISSUE TITLE
Issue on the hotkey to fill in username and password 

### ISSUE THREAD

**Issue by joyarzun** [geluk/pass-winmenu#108]
Hello

I have the following config:
```
  - 
    hotkey: 'ctrl alt shift p'
    action: 'decrypt-password'
    options:
        copy-to-clipboard: false
        type-username: true
        type-password: true
```

When I use the hotkey doesn't fill in the username, only fills in the password. For example, I go to gitlab.com login page, click on the username then press the crtl+alt+shift+p hotkey, and it appears the menu to choose the password, I click on one and I got the following:

![image](https://user-images.githubusercontent.com/828211/189275224-17e06c09-35b0-4c7e-bb91-d500d78a63bb.png)

The username and the "tab" is missing. This situation happens with other sites also. The issue started when I updated the pass-winmenu but now I don't remember which version works. I've tested previous versions with no luck. What could be wrong?

Any help will be appreciated

Using:
- pass-winmenu v1.13
- Win10
- Chrome 104.0.5112.102 (Build oficial) (64 bits)
