### ISSUE TITLE
Provide a mechanism by which the username associated with a password can be retrieved/copied

### ISSUE THREAD

**Issue by IvanMalison** [geluk/pass-winmenu#76]
One of the things to note here is that it seems that there is not really consensus around which heading this username should be stored under:

Some that I've seen:

- user
- username
- account
- name

See https://github.com/android-password-store/Android-Password-Store/issues/761

**Comment by geluk** [comment]
One way this can be done is by creating a `password-field` hotkey binding. Given a password file that looks like this:
```
your-password-here
Username: example
Email: example@example.com
Backup-Code: abc
Backup-Code: def
Backup-Code: ghi
```

The value of a field can be retrieved using a `password-field` hotkey action. For instance, to retrieve the username:
```yml
hotkeys:
  [ ... ]
  - 
    hotkey: 'ctrl alt shift u'
    action: 'password-field'
    options:
        field-name: 'Username'
        copy-to-clipboard: true
        type: true
```
Modifying the `copy-to-clipboard` and `type` fields as desired.

Of course, this only works if you consistently use the same key name throughout.
To retrieve the value of arbitrary keys, you can leave out the `field-name` altogether. When you execute the hotkey, pass-winmenu will prompt you with a dialog that will let you select the key whose value you want to retrieve.
