### ISSUE TITLE
field-name option not working

### ISSUE THREAD

**Issue by uri** [geluk/pass-winmenu#93]
I have the following config

```yaml
 - 
    hotkey: 'ctrl alt shift l'
    action: 'decrypt-password'
    options:
        field-name: 'login'
        copy-to-clipboard: true
        type-username: true
        type-password: true
```

However it doesn't seem to work. I have another password that uses the field `username` and it does work (even with this config)

The documentation mentions that a prompt will be presented if this option is not provided but that doesn't seem to be the case either.
